server:
  port: 7070

logging:
  level:
    cn.bunny.service.mapper: info
    cn.bunny.service.controller: info
    cn.bunny.service.service: info
    root: info
  pattern:
    dateformat: HH:mm:ss:SSS
#  file:
#    path: "logs/${spring.application.name}"
#    name: "logs/${spring.application.name}"

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看日志

bunny:
  master:
    host: 192.168.3.137
    port: 3306
    database: auth_admin
    username: root
    password: "123456"

  redis:
    host: 192.168.3.137
    port: 6379
    database: 0
    password: "123456"

  minio:
    endpointUrl: "http://192.168.3.137:9000" # 连接地址
    accessKey: bunny # 用户名
    secretKey: "12345678" # 登录密码
    bucket-name: auth-admin # 指定哪个桶

  backPath: "D:\\MyData\\backup"
