bunny:
  datasource1:
    host: 192.168.3.98
    port: 3304
    sqlData: auth_admin
    username: root
    password: "02120212"
  datasource2:
    host: 106.15.251.123
    port: 3305
    sqlData: auth_i18n
    username: root
    password: "02120212"

  redis:
    host: 192.168.3.98
    port: 6379
    database: 0
    password: "123456"

  minio:
    endpointUrl: "http://192.168.3.98:9000"
    accessKey: bunny
    secretKey: "02120212"
    bucket-name: bunny-bbs
