server:
  port: 7070

logging:
  level:
    cn.bunny.service.mapper: info
    cn.bunny.service.controller: info
    cn.bunny.service.service: info
    root: info
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "/logs/${spring.application.name}"

#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看日志

bunny:
  master:
    host: 192.168.3.98
    port: 3304
    database: auth_admin
    username: root
    password: "02120212"

  redis:
    host: 192.168.3.98
    port: 6379
    database: 0
    password: "123456"

  minio:
    endpointUrl: "http://192.168.3.98:9000"
    accessKey: bunny
    secretKey: "02120212"
    bucket-name: auth-admin

  backPath: "D:\\MyData\\backup"
  bashPath: "D:\\MyData"
