server:
  port: 8000

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: isDeleted

logging:
  level:
    cn.bunny.service.mapper: warn
    cn.bunny.service.controller: warn
    cn.bunny.service.service: warn
    root: warn
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"

# 线上禁用文档
knife4j:
  enable: true
  production: true

bunny:
  master:
    #    host: 106.15.251.123
    #    port: 3306
    host: 192.168.3.98
    port: 3304
    database: auth_admin
    username: root
    password: "02120212"
    databaseBackupDir: "/home/backup/"

  redis:
    host: 47.120.65.66
    port: 6379
    database: 0
    password: "02120212"

  minio:
    endpointUrl: "http://116.196.101.14:9000"
    accessKey: bunny
    secretKey: "02120212"
    bucket-name: auth-admin