server:
  port: 8000

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: isDeleted
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    cn.bunny.service.mapper: warn
    cn.bunny.service.controller: warn
    cn.bunny.service.service: warn
    root: warn
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"

# 线上禁用文档
knife4j:
  enable: true
  production: true

#  rabbitmq:
#    host: ${bunny.rabbitmq.host}
#    port: ${bunny.rabbitmq.port}
#    username: ${bunny.rabbitmq.username}
#    password: ${bunny.rabbitmq.password}
#    virtual-host: ${bunny.rabbitmq.virtual-host}
#    publisher-confirm-type: correlated # 交换机确认
#    publisher-returns: true # 队列确认
#    listener:
#      simple:
#        acknowledge-mode: manual # 手动处理消息
#    connection-timeout: 1s # 设置MQ连接超时时间
#    template:
#      retry:
#        enabled: true # 失败重试
#        initial-interval: 1000ms # 失败后初始时间
#        multiplier: 1 # 失败后下次等待时长倍数 initial-interval * multiplier
#        max-attempts: 3 # 最大重试次数

bunny:
  master:
    host: 192.168.3.98
    port: 3304
    database: auth_admin
    username: root
    password: "02120212"

  redis:
    host: 192.168.3.98
    port: 6379
    database: 0
    password: "123456"

  minio:
    endpointUrl: "http://192.168.3.98:9000"
    accessKey: bunny
    secretKey: "02120212"
    bucket-name: auth-admin

  backPath: "/www/root/backup"
  bashPath: "/www/root/server"