server:
  port: 7070

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: isDeleted

logging:
  level:
    cn.bunny.service.mapper: warn
    cn.bunny.service.controller: warn
    cn.bunny.service.service: warn
    root: warn
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"

# 线上禁用文档
knife4j:
  enable: true
  production: true

bunny:
  datasource1:
    host: 192.168.3.98
    port: 3304
    sqlData: auth_admin
    username: root
    password: "02120212"

  redis:
    host: 192.168.3.98
    port: 6379
    database: 0
    password: "123456"

  minio:
    endpointUrl: "http://192.168.3.98:9000"
    accessKey: bunny
    secretKey: "02120212"
    bucket-name: auth-admin