server:
  port: 8000

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      logic-delete-field: isDeleted
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看日志

logging:
  level:
    cn.bunny.service.mapper: warn
    cn.bunny.service.controller: warn
    cn.bunny.service.service: warn
    root: warn
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"

# 线上禁用文档
knife4j:
  enable: true
  production: true

bunny:
  master:
    host: rm-bp12z6hlv46vi6g8mro.mysql.rds.aliyuncs.com
    port: 3306
    database: auth_admin
    username: auth_admin_prod
    password: 0212auth_admin

  redis:
    host: 47.120.65.66
    port: 6379
    database: 0
    password: "02120212"

  minio:
    endpointUrl: "http://116.196.101.14:9000"
    accessKey: bunny
    secretKey: "02120212"
    bucket-name: auth-admin

  backPath: "/www/root/backup"
  bashPath: "/www/root/server"