server:
  port: 7070

logging:
  level:
    cn.bunny.service.mapper: info
    cn.bunny.service.controller: info
    cn.bunny.service.service: info
    root: info
  pattern:
    dateformat: HH:mm:ss:SSS
  file:
    path: "logs/${spring.application.name}"
    name: "logs/${spring.application.name}"

# mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看日志

bunny:
  master:
    host: 192.168.3.137 # localhost
    port: 3306
    database: auth_admin
    username: root
    password: "123456"

  redis:
    host: 192.168.3.137
    port: 6379
    database: 0
    password: "123456"

dromara:
  local-plus:
    # 访问域名，例如：“http://127.0.0.1:8030/{path-patterns}”，注意后面要和 path-patterns 名字一样
    domain: /api/local-file
    # 访问路径，使用本地在SpringSecurity中要配置权限，如果是和我一样就不用修改了，如果不是api开头，上线需要配置nginx
    path-patterns: /api/local-file/**
    storage-path: D:/Temp/ # 存储路径
    # storage-path: ~/bunny-admin/temp # 存储路径
    base-path: "" # 基础路径
  minio:
    endpointUrl: "http://192.168.3.137:9000" # 连接地址
    accessKey: bunny # 用户名
    secretKey: "12345678" # 登录密码
    bucket-name: auth-admin # 指定哪个桶
    base-path: "" # 基础路径